<?php

/**
 * @file
 * Contains custom_data.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_data_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the custom_resource module.
    case 'help.page.custom_data':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My custom resource data') . '</p>';
      return $output;

    default:
  }
}
